SIM=icarus
TOPLEVEL_LANG ?= verilog
PWD=$(shell pwd)
VERILOG_SOURCES=$(PWD)/../../hdl/mux/mux_8to1_8b.v

TOPLEVEL := mux_8to1_8b
MODULE := test_mux_8to1_8b

include $(shell cocotb-config --makefiles)/Makefile.sim
