SIM=icarus
TOPLEVEL_LANG = systemverilog
PWD=$(shell pwd)
VERILOG_SOURCES=$(PWD)/../../hdl/phase_acc.sv
TOPLEVEL := phase_acc
MODULE := test_phase_acc

include $(shell cocotb-config --makefiles)/Makefile.sim
