SIM=icarus
TOPLEVEL_LANG = systemverilog
PWD=$(shell pwd)
VERILOG_SOURCES=$(PWD)/../../hdl/reg/reg_8x8b.sv
TOPLEVEL := reg_8x8b
MODULE := test_reg_8x8b

include $(shell cocotb-config --makefiles)/Makefile.sim
