SIM=icarus
TOPLEVEL_LANG = systemverilog
PWD=$(shell pwd)
VERILOG_SOURCES=$(PWD)/../../hdl/rom/sin_rom.sv
TOPLEVEL := sin_rom
MODULE := test_sin_rom

include $(shell cocotb-config --makefiles)/Makefile.sim
